[package]
name = "fast-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
rayon = "1.7.0"

# Files Formats
pro_csv = "0.1.1"

# Compression Formats
zip = "0.6.4"
